# -*- coding: utf-8 -*-
"""implicit-hate-irony-detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VU-9wq4Lzfg6kmYJs5Z5WzeykyzwCu3c
"""

import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("No GPU detected.")
    print("In Colab: Runtime → Change runtime type → T4 GPU")

!pip install -q datasets

from datasets import load_dataset

dataset = load_dataset("SALT-NLP/ImplicitHate")

print(dataset)

print("Available splits:")

for split in dataset:
    print(f"{split}: {len(dataset[split])} examples")

for split in dataset:
    print(f"\n{split} columns:")
    print(dataset[split].column_names)

example = dataset[list(dataset.keys())[0]][0]

example

from collections import Counter

labels = Counter(dataset["train"]["implicit_class"])

for label, count in labels.most_common():
    print(f"{label}: {count}")

import pandas as pd
from sklearn.model_selection import train_test_split


df = dataset["train"].to_pandas()

# Remove "other"
df = df[df["implicit_class"] != "other"].copy()


df["category"] = df["implicit_class"].str.rsplit("_", n=1).str[-1]

# Rename categories
category_names = {
    "grievance": "Grievance",
    "incitement": "Incitement",
    "stereotypical": "Stereotypes",
    "inferiority": "Inferiority",
    "irony": "Irony",
    "threatening": "Threats"
}

df["category"] = df["category"].map(category_names)


print("Category counts:")
print(df["category"].value_counts())

# 80% train, 20% temporary
train_df, temp_df = train_test_split(
    df,
    test_size=0.20,
    stratify=df["category"],
    random_state=42
)


# 10% development, 10% test
dev_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["category"],
    random_state=42
)

print("Train:", len(train_df))
print("Dev:", len(dev_df))
print("Test:", len(test_df))

print("TRAIN")
print(train_df["category"].value_counts())
print()

print("DEV")
print(dev_df["category"].value_counts())
print()

print("TEST")
print(test_df["category"].value_counts())

print("TRAIN (%)")
print((train_df["category"].value_counts(normalize=True) * 100).round(2))
print()

print("DEV (%)")
print((dev_df["category"].value_counts(normalize=True) * 100).round(2))
print()

print("TEST (%)")
print((test_df["category"].value_counts(normalize=True) * 100).round(2))

from google.colab import drive
drive.mount('/content/drive')


import os

save_path = "/content/drive/MyDrive/implicit_hate_project"
os.makedirs(save_path, exist_ok=True)


train_df.to_csv(f"{save_path}/train.csv", index=False)
dev_df.to_csv(f"{save_path}/dev.csv", index=False)
test_df.to_csv(f"{save_path}/test.csv", index=False)

print("Saved successfully!")
print(f"Files are in: {save_path}")

!pip install -q transformers datasets accelerate evaluate scikit-learn

import pandas as pd

save_path = "/content/drive/MyDrive/implicit_hate_project"

train_df = pd.read_csv(f"{save_path}/train.csv")
dev_df = pd.read_csv(f"{save_path}/dev.csv")
test_df = pd.read_csv(f"{save_path}/test.csv")

print("Train:", len(train_df))
print("Dev:", len(dev_df))
print("Test:", len(test_df))

print(train_df.columns)
print(train_df.head())

label2id = {
    "Grievance": 0,
    "Incitement": 1,
    "Stereotypes": 2,
    "Inferiority": 3,
    "Irony": 4,
    "Threats": 5
}

id2label = {v: k for k, v in label2id.items()}

train_df["label"] = train_df["category"].map(label2id)
dev_df["label"] = dev_df["category"].map(label2id)
test_df["label"] = test_df["category"].map(label2id)

print(train_df[["category", "label"]].head())

print("Missing train text:", train_df["post"].isna().sum())
print("Missing dev text:", dev_df["post"].isna().sum())
print("Missing test text:", test_df["post"].isna().sum())
print("Missing train labels:", train_df["label"].isna().sum())
print("Missing dev labels:", dev_df["label"].isna().sum())
print("Missing test labels:", test_df["label"].isna().sum())
print("Missing train labels:", train_df["label"].isna().sum())
print("Missing dev labels:", dev_df["label"].isna().sum())
print("Missing test labels:", test_df["label"].isna().sum())
print(sorted(train_df["label"].unique()))
print(sorted(dev_df["label"].unique()))
print(sorted(test_df["label"].unique()))
import torch

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

from transformers import AutoTokenizer

model_name = "roberta-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Tokenizer loaded successfully!")

def tokenize_data(df):
    return tokenizer(
        df["post"].tolist(),
        padding=True,
        truncation=True,
        max_length=128
    )

train_encodings = tokenize_data(train_df)
dev_encodings = tokenize_data(dev_df)
test_encodings = tokenize_data(test_df)

print("Train examples:", len(train_encodings["input_ids"]))
print("Dev examples:", len(dev_encodings["input_ids"]))
print("Test examples:", len(test_encodings["input_ids"]))

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base",
    num_labels=6,
    id2label=id2label,
    label2id=label2id
)

print("RoBERTa classification model loaded!")

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)
from datasets import Dataset



model_name = "roberta-base"



tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_data(df):
    return tokenizer(
        df["post"].tolist(),
        padding=True,
        truncation=True,
        max_length=128
    )

train_encodings = tokenize_data(train_df)
dev_encodings = tokenize_data(dev_df)
test_encodings = tokenize_data(test_df)



train_dataset = Dataset.from_dict({
    "input_ids": train_encodings["input_ids"],
    "attention_mask": train_encodings["attention_mask"],
    "labels": train_df["label"].tolist()
})

dev_dataset = Dataset.from_dict({
    "input_ids": dev_encodings["input_ids"],
    "attention_mask": dev_encodings["attention_mask"],
    "labels": dev_df["label"].tolist()
})

test_dataset = Dataset.from_dict({
    "input_ids": test_encodings["input_ids"],
    "attention_mask": test_encodings["attention_mask"],
    "labels": test_df["label"].tolist()
})



model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=6,
    id2label=id2label,
    label2id=label2id
)

print("RoBERTa model ready for fine-tuning.")
print("Train:", len(train_dataset))
print("Dev:", len(dev_dataset))
print("Test:", len(test_dataset))

import torch
import numpy as np
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, f1_score


if not torch.cuda.is_available():
    raise RuntimeError("GPU not available. Please enable the T4 GPU in Colab.")

device = torch.device("cuda")
print("Using GPU:", torch.cuda.get_device_name(0))


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    return {
        "accuracy": accuracy_score(labels, predictions),
        "macro_f1": f1_score(labels, predictions, average="macro"),
        "weighted_f1": f1_score(labels, predictions, average="weighted")
    }


training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/implicit_hate_project/roberta_baseline",


    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,


    eval_strategy="epoch",
    save_strategy="epoch",


    metric_for_best_model="macro_f1",
    greater_is_better=True,
    load_best_model_at_end=True,


    learning_rate=2e-5,
    weight_decay=0.01,


    logging_strategy="steps",
    logging_steps=50,


    fp16=True,


    seed=42,


    report_to="none"
)


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics
)


trainer.train()

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)
import numpy as np


test_results = trainer.predict(test_dataset)


test_predictions = np.argmax(test_results.predictions, axis=1)
test_labels = test_results.label_ids


accuracy = accuracy_score(test_labels, test_predictions)
macro_f1 = f1_score(test_labels, test_predictions, average="macro")
weighted_f1 = f1_score(test_labels, test_predictions, average="weighted")

print("TEST SET RESULTS")
print("----------------")
print(f"Accuracy:     {accuracy:.4f}")
print(f"Macro-F1:     {macro_f1:.4f}")
print(f"Weighted-F1:  {weighted_f1:.4f}")


print("\nPER-CATEGORY RESULTS")
print("--------------------")

print(
    classification_report(
        test_labels,
        test_predictions,
        target_names=[
            "Grievance",
            "Incitement",
            "Stereotypes",
            "Inferiority",
            "Irony",
            "Threats"
        ],
        digits=4
    )
)


cm = confusion_matrix(test_labels, test_predictions)

print("\nCONFUSION MATRIX")
print("----------------")
print(cm)

import os
import torch
import numpy as np
import pandas as pd

from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer

project_dir = "/content/drive/MyDrive/implicit_hate_project"

label2id = {
    "Grievance": 0,
    "Incitement": 1,
    "Stereotypes": 2,
    "Inferiority": 3,
    "Irony": 4,
    "Threats": 5
}

id2label = {v: k for k, v in label2id.items()}


test_df = pd.read_csv(
    os.path.join(project_dir, "test.csv")
)

test_df["label"] = test_df["category"].map(label2id)


checkpoints = [
    "checkpoint-314",
    "checkpoint-628",
    "checkpoint-942"
]

for checkpoint in checkpoints:

    print("\n" + "=" * 60)
    print(checkpoint)
    print("=" * 60)

    model_path = os.path.join(
        project_dir,
        "roberta_baseline",
        checkpoint
    )


    model = AutoModelForSequenceClassification.from_pretrained(
        model_path
    )

    model = model.to("cuda")
    model.eval()

    print("Number of labels:", model.config.num_labels)
    print("Labels:", model.config.id2label)


    bias = model.classifier.out_proj.bias.detach().cpu().numpy()

    print("\nClassifier bias:")
    for i, value in enumerate(bias):
        print(f"{i} {id2label[i]:15s}: {value:.4f}")


    tokenizer = AutoTokenizer.from_pretrained(
        model_path
    )


    small_df = test_df.iloc[:10].copy()

    encodings = tokenizer(
        small_df["post"].tolist(),
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    encodings = {
        key: value.to("cuda")
        for key, value in encodings.items()
    }


    with torch.no_grad():
        logits = model(**encodings).logits

    predictions = torch.argmax(
        logits,
        dim=1
    ).cpu().numpy()

    print("\nFirst 10 predictions:")

    for i, pred in enumerate(predictions):
        print(
            f"{i}: "
            f"TRUE={small_df.iloc[i]['category']:15s} "
            f"PRED={id2label[int(pred)]}"
        )


    print("\nAverage logits for each class:")

    avg_logits = logits.mean(dim=0).cpu().numpy()

    for i, value in enumerate(avg_logits):
        print(
            f"{id2label[i]:15s}: {value:.4f}"
        )

import json
import os

state_path = "/content/drive/MyDrive/implicit_hate_project/roberta_baseline/checkpoint-942/trainer_state.json"

with open(state_path, "r") as f:
    state = json.load(f)

print("Best checkpoint:")
print(state.get("best_model_checkpoint"))

print("\nBest metric:")
print(state.get("best_metric"))

print("\nEvaluation history:")
for x in state["log_history"]:
    if "eval_macro_f1" in x:
        print(x)

import pandas as pd
import os


project_dir = "/content/drive/MyDrive/implicit_hate_project"

prediction_path = os.path.join(
    project_dir,
    "test_predictions.csv"
)

df = pd.read_csv(prediction_path)


errors = df[df["true_label"] != df["predicted_label"]].copy()

print("Total test examples:", len(df))
print("Misclassified examples:", len(errors))
print("Correct examples:", len(df) - len(errors))


error_counts = (
    errors
    .groupby(["true_label", "predicted_label"])
    .size()
    .reset_index(name="count")
    .sort_values(
        ["true_label", "count"],
        ascending=[True, False]
    )
)

print("\n========================================")
print("ERROR COUNTS: TRUE → PREDICTED")
print("========================================")

print(error_counts.to_string(index=False))


print("\n========================================")
print("MISCLASSIFIED EXAMPLES")
print("========================================")

for true_label in errors["true_label"].unique():

    true_errors = errors[
        errors["true_label"] == true_label
    ]

    print("\n" + "=" * 70)
    print(f"TRUE CATEGORY: {true_label}")
    print("=" * 70)

    for predicted_label in true_errors["predicted_label"].unique():

        group = true_errors[
            true_errors["predicted_label"] == predicted_label
        ]

        print(
            f"\n--- Predicted as {predicted_label} "
            f"({len(group)} examples) ---"
        )

        for i, (_, row) in enumerate(group.iterrows(), start=1):

            print(f"\nExample {i}")
            print("Tweet:", row["post"])



error_output_path = os.path.join(
    project_dir,
    "misclassified_examples.csv"
)

errors.to_csv(
    error_output_path,
    index=False
)

print("\n========================================")
print("Saved misclassified examples to:")
print(error_output_path)
print("========================================")

import pandas as pd
import os


project_dir = "/content/drive/MyDrive/implicit_hate_project"
input_file = os.path.join(project_dir, "misclassified_examples.csv")
output_file = os.path.join(project_dir, "major_confusion.csv")


major_pairs = [
    ("Grievance", "Incitement", 22),
    ("Grievance", "Stereotypes", 14),
    ("Grievance", "Inferiority", 8),
    ("Grievance", "Threats", 8),
    ("Incitement", "Grievance", 17),
    ("Incitement", "Stereotypes", 15),
    ("Incitement", "Threats", 12),
    ("Inferiority", "Irony", 14),
    ("Inferiority", "Incitement", 9),
    ("Inferiority", "Grievance", 5),
    ("Irony", "Inferiority", 12),
    ("Irony", "Grievance", 6),
    ("Irony", "Threats", 5),
    ("Stereotypes", "Grievance", 15),
    ("Stereotypes", "Incitement", 11),
    ("Stereotypes", "Inferiority", 6),
    ("Threats", "Incitement", 7)
]


df = pd.read_csv(input_file)

print("Loaded:", len(df), "misclassified examples")


selected_parts = []

for true_label, predicted_label, expected_count in major_pairs:

    subset = df[
        (df["true_label"] == true_label) &
        (df["predicted_label"] == predicted_label)
    ].copy()

    actual_count = len(subset)

    print(
        f"{true_label} → {predicted_label}: "
        f"{actual_count} examples (expected {expected_count})"
    )


    subset.insert(
        0,
        "confusion_pair",
        f"{true_label} → {predicted_label}"
    )

    selected_parts.append(subset)


major_confusion = pd.concat(selected_parts, ignore_index=True)


major_confusion["annotation"] = ""
major_confusion["notes"] = ""


major_confusion = major_confusion[
    [
        "confusion_pair",
        "true_label",
        "predicted_label",
        "post",
        "annotation",
        "notes"
    ]
]


major_confusion.to_csv(output_file, index=False)

print("\n" + "=" * 60)
print("DONE")
print("=" * 60)
print("Saved to:")
print(output_file)
print("\nTotal examples:", len(major_confusion))
print("Expected examples: 177")

from google.colab import files

file_path = "/content/drive/MyDrive/implicit_hate_project/major_confusion.csv"

files.download(file_path)













